#!/usr/bin/env python3

import sys

from pathlib import Path

DEFAULT_PREFIX = Path.home() / 'install' / 'master'


def filter_none(paths):
    return [path for path in paths if path is not None]


def main():
    if len(sys.argv) > 1:
        prefix = Path(sys.argv[1]).absolute()
    else:
        prefix = DEFAULT_PREFIX

    prefix.mkdir(parents=True, exist_ok=True)

    activate_file = prefix / 'activate'

    template_file = Path(__file__).parent / 'activate'
    with template_file.open('r') as tf:
        template = tf.read()

    activate = template.replace('__PREFIX__', str(prefix))

    with activate_file.open(mode='w') as f:
        f.write(activate)

    print('Created environment at %s' % (str(prefix),))
    print('Please run "source %s" to start the environment\n' %
          (str(activate_file)))


if __name__ == '__main__':
    main()

#  vim: set ts=8 sw=4 tw=80:
