#!/usr/bin/env python3

import sys

from pathlib import Path

DEFAULT_PREFIX = Path.home() / 'install' / 'master'


def filter_none(paths):
    return [path for path in paths if path is not None]


def main():
    if len(sys.argv) > 1:
        prefix = Path(sys.argv[1]).absolute()
    else:
        prefix = DEFAULT_PREFIX

    prefix.mkdir(parents=True, exist_ok=True)

    activate_file = prefix / 'activate'

    with activate_file.open(mode='w') as f:
        f.write('PREFIX=%s\n' % (prefix,))
        f.write('export INSTALL_PREFIX=$PREFIX\n')
        f.write('export LD_LIBRARY_PATH=$PREFIX/lib\n')
        f.write('export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig\n')
        f.write('export PATH=$PREFIX/sbin:$PREFIX/bin:$PATH\n')
        f.write('export PYTHONPATH=$PREFIX/lib/python2.7/site-packages:' +
                '$PTYHONPATH\n')


if __name__ == '__main__':
    main()

#  vim: set ts=8 sw=4 tw=80:
